### PR TITLE
Fix integer truncating issue in fan percentages

### PR DESCRIPTION
**Pull request by leokeba**
Hi, I made a quick fix after I noticed that fan percentages always appeared off by one. I did some quick testing, seems to resolve the issue, but feel free to test it as well or suggest a better way if this one is not optimal.

Thanks for the good work.

### CODE REVIEW

**Comment by xperiments** [comment]
Hey leokeka, thanks for the comment.

I will no be accepting pull requests as the license model will no me let me to accept pulls.

Open an issue explaining the problem, them I will try to fix myself.

Thanks anyway, don't take it wrong

**Comment by leokeba** [comment]
Well this is unfortunate. Can you elaborate about this license model thing ? I don't see any license anywhere on the repo so I'm just curious about what might be the issue. But that's your decision for sure.

I guess I will be maintaining my own fork for now, as there are many features I'm thinking of already and I don't wanna bother you or wait for you to implement them, feel free to backport anything if you want.

**Comment by xperiments** [comment]
Atm the license is this one

https://choosealicense.com/no-permission/

I will be updating the license this week. It will be a dual license where I need to decide the open source part (GPLv3 or cc-by-nc-sa) and a OEM payed license

So I need to maintain my fork without any colaborator because if not I will break the licenses and then I can't do my OEM

So actually you don't have permisión about my code, please wait until the license comes out to make your fork or do it privately

**Comment by xperiments** [comment]
ATM you can't legally fork. You can download the zip & work privately on your own.

I don't see the problem w bambu. BBS is GPLv3. Yes uses some private API but I am not using any of it's private api. Also I have been in contact w BBL without any problem so?

My OEM think is just to don't let ppl sell my work. Maybe I have not the intention to do so. Wait for this week for more news

**Comment by xperiments** [comment]
And this phrase explains all, also why I don't let pulls 
"When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you."

“nobody” starts including you.

**Comment by leokeba** [comment]
Okay, I will remove my fork for now.

Not sure I understand the relation with Bambu Studio, since they are the ones maintaining it, and the network plugin they use for talking with the printer is not open source.

I am not an expert in software licensing, so I won't go over my head, but I think the GPL family pretty much does what you are looking for, which is preventing anyone else to use your software in commercial applications, unless you grant them a specific exception, which you can do in exchange for money.

That would allow people like me to fork it and modify it to their needs, but we would have to release it under a compatible licence so you would be protected. At least that's my understanding, but once again I am no expert and this is not legal advice.

Anyway, thanks for taking the time to answer me.

**Pull request closed without merging**
